### ISSUE TITLE
No receiving refreshToken in authorization response.

### ISSUE THREAD

**Issue by gwilakers** [yanatan16/passport-youtube-v3#12]
I have noticed in the past few months that I am no longer receiving a refreshToken in the response back from the auth endpoint. Is there an update that needs to be made to this package in order to continue getting the property? Let me know where I can help or if you need any additional information. I am using a pretty standard implementation of the package so there shouldn't be anything project specific.

**Comment by gwilakers** [comment]
It looks like if you include:

      "authorizationParams": { 
        "access_type": "offline", 
        "approval_prompt": "auto" 
      }

in the options given to the strategy, you no longer get back a refreshToken. I am guessing this overwrites the defaults given by you in the authorizationParams override function, but puts them in the wrong part of the request given to Google? Let me know if you have any insight to this or if you can replicate to confirm.

**Comment by yanatan16** [comment]
@gwilakers Not sure. I haven't used this project in quite a while. Its possible Google has changed their policies about refresh tokens. Let me know if you find out.

**Comment by gwilakers** [comment]
@yanatan16 Yeah, it appears as though including those options causes a conflict when setting the access_type property and it does not get sent to YouTube at all. I didn't dig too deep into the code to see what causes that, but removing that from our config seems to fix the issue. I'll close this issue, just wanted to you be aware of it in case someone else runs into it. Thanks!
